##
# environment.yml: Specification of a conda environment for use with
#      Q# interoperability samples.
##
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.
##

name: qsharp-samples
channels:
    - conda-forge
    - https://solidrepo.blob.core.windows.net/release/1806.3001/src/python/bin/package
dependencies:
    - python==3.6.4
    - numpy
    - scipy
    - future
    - qutip
    - matplotlib
    - ipyparallel
    - py
#    - qsharp=0.2.1806.3001
    - pip:
        - qinfer
        - duecredit
        - mpltools
	- git+https://github.com/pythonnet/pythonnet